spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tenanttable
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true

  mail:
    properties:
      mail:
        debug: false

cookie:
  secure: false